name: somun_flutter
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/deniza/somun-flutter

environment:
  sdk: '>=2.18.6 <3.0.0'

# Add regular dependencies here.
dependencies:

dev_dependencies:
  lints: ^2.0.1
